# Generated by Django 4.2.20 on 2025-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluser',
            name='teml',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cluser',
            name='tphne',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
