# Generated by Django 4.2.20 on 2025-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cluser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluser',
            name='date_retraite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
