# Generated by Django 4.2.20 on 2025-04-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cluser_date_retraite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
