# Generated by Django 4.2.20 on 2025-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='adresse',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administration',
            name='boite_postale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='email',
            field=models.EmailField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administration',
            name='structure_superieure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='type_structure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='ville',
            field=models.CharField(default=23042025, max_length=100),
            preserve_default=False,
        ),
    ]
