# Generated by Django 4.2.20 on 2025-04-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clvisite',
            name='hvst',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de visite'),
        ),
    ]
