# Generated by Django 4.2.20 on 2025-04-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaire', '0001_initial'),
        ('visite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClProgrammeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddpvst', models.DateField(verbose_name='Date programmée de visite')),
                ('hdbt', models.TimeField(verbose_name='Heure début')),
                ('hhf', models.TimeField(blank=True, null=True, verbose_name='Heure fin')),
                ('tsttpvst', models.CharField(choices=[('confirmé', 'Confirmé'), ('annulé', 'Annulé')], default='confirmé', max_length=60, verbose_name='Statut du programme de visite')),
                ('motif', models.CharField(blank=True, choices=[('visiteur occupé', 'Visiteur occupé'), ('directeur occupé', 'Directeur occupé')], max_length=50, verbose_name="Motif (en cas d'empêchement)")),
                ('idvst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visite.clvisite', verbose_name='Visite')),
                ('secretaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretaire.clsecretaire', verbose_name='Secrétaire')),
            ],
        ),
    ]
